In [33]:
import torch
import dgl 
num_nodes, num_edges = 100, 200
src_nodes = torch.randint(0, num_nodes, (num_edges,))
dst_nodes = torch.randint(0, num_nodes, (num_edges,))
graph = dgl.graph((src_nodes, dst_nodes))
graph = dgl.add_self_loop(graph)
graph

Graph(num_nodes=100, num_edges=300,
      ndata_schemes={}
      edata_schemes={})

In [48]:
graph.num_nodes()

100

In [34]:
graph.ndata['features'] = torch.randn(graph.number_of_nodes(), 128)
graph

Graph(num_nodes=100, num_edges=300,
      ndata_schemes={'features': Scheme(shape=(128,), dtype=torch.float32)}
      edata_schemes={})

In [35]:
graph.nodes()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
dgl.node_subgraph(graph, [1, 3, 5])

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={'features': Scheme(shape=(128,), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [37]:
print(dgl.node_subgraph(graph, [1, 3, 5]).edges())

(tensor([0, 1, 2]), tensor([0, 1, 2]))


In [38]:
dgl.bfs_nodes_generator(graph, [0])

(tensor([0]),
 tensor([54, 83, 45,  8]),
 tensor([71, 84, 14, 37, 74]),
 tensor([50, 23, 42, 46, 61, 91, 47]),
 tensor([78, 22, 51, 80, 15, 86, 16, 52, 90, 21, 34,  6, 31]),
 tensor([58, 11, 26,  1, 18, 93, 59, 96, 82,  2, 72, 55, 88,  7, 68, 24]),
 tensor([94, 35, 56, 92, 48, 81, 10, 27, 29, 77, 87, 76, 28, 49, 98, 40, 63, 62,
         67, 75, 44, 38,  3]),
 tensor([95, 25, 73, 60, 64,  5, 12, 65, 53, 99]),
 tensor([57, 19, 33]),
 tensor([17, 70]))

In [39]:
dgl.bfs_nodes_generator(graph, [1])

(tensor([1]),
 tensor([27, 29]),
 tensor([12, 51, 77, 84]),
 tensor([24,  8, 26,  0, 92, 42]),
 tensor([40, 16,  3, 74, 81, 10, 54, 83, 45, 34, 86]),
 tensor([96, 82,  2, 37, 60, 64, 52,  5, 71, 14, 59]),
 tensor([28, 49, 55, 98, 93, 63, 31, 50, 47, 33, 62, 72, 23, 46, 61, 91, 76]),
 tensor([68, 53, 22, 87, 88,  7, 78,  6, 17, 70, 80, 15, 90, 21]),
 tensor([65, 73, 67, 75, 44, 38, 58, 11, 18]),
 tensor([19, 99, 94, 35, 56, 48]),
 tensor([95, 25]),
 tensor([57]))

In [40]:
dgl.readout_nodes(graph, 'features', op="mean").shape

torch.Size([1, 128])

In [47]:
dgl.khop_graph(graph, 1)

Graph(num_nodes=100, num_edges=300,
      ndata_schemes={'features': Scheme(shape=(128,), dtype=torch.float32)}
      edata_schemes={})

In [50]:
dgl.khop_in_subgraph(graph, [1], 1)

tensor([0])