In [1]:
import torch
import dgl 
num_nodes, num_edges = 100, 200
src_nodes = torch.randint(0, num_nodes, (num_edges,))
dst_nodes = torch.randint(0, num_nodes, (num_edges,))
graph = dgl.graph((src_nodes, dst_nodes))
graph = dgl.add_self_loop(graph)
graph

Graph(num_nodes=100, num_edges=300,
      ndata_schemes={}
      edata_schemes={})

In [2]:
graph.num_nodes()

100

In [3]:
graph.ndata['features'] = torch.randn(graph.number_of_nodes(), 128)
graph

Graph(num_nodes=100, num_edges=300,
      ndata_schemes={'features': Scheme(shape=(128,), dtype=torch.float32)}
      edata_schemes={})

In [14]:
graph.nodes()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
dgl.node_subgraph(graph, [1, 3, 5])

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={'features': Scheme(shape=(128,), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [16]:
print(dgl.node_subgraph(graph, [1, 3, 5]).edges())

(tensor([0, 1, 2]), tensor([0, 1, 2]))


In [17]:
dgl.bfs_nodes_generator(graph, [0])

(tensor([0]),
 tensor([33, 65, 96, 97]),
 tensor([ 1, 72, 44, 47, 89, 99,  6, 18]),
 tensor([24, 62, 50, 80,  3,  5, 94, 83, 70, 41, 17,  2, 84]),
 tensor([32, 75, 92, 81, 43, 11, 90, 46, 82, 39, 13, 42, 78, 28, 77,  8, 52, 63,
         29]),
 tensor([91, 64, 40, 73, 58, 98, 48, 21,  9, 53, 88, 55, 87, 14, 59, 54, 67, 60]),
 tensor([22, 56, 76, 36, 31, 10, 27, 35, 85, 12, 95, 37]),
 tensor([19, 49, 68, 86, 69]),
 tensor([ 4, 26, 25]),
 tensor([93]))

In [22]:
dgl.bfs_nodes_generator(graph, [1])

(tensor([1]),
 tensor([24]),
 tensor([83, 32]),
 tensor([78, 28, 33, 91, 64]),
 tensor([58, 87, 14, 22, 92, 56]),
 tensor([53, 43, 12, 40, 99,  0, 41,  6, 94]),
 tensor([98, 72, 48, 21,  9, 17, 86, 69, 70, 65, 96, 97,  3,  2, 13, 42]),
 tensor([76, 62, 50, 88, 36, 80, 31, 10, 27, 77,  8, 73, 26, 39, 25, 89, 55, 44,
         47, 18, 82, 52, 84, 63, 11]),
 tensor([75, 81, 90, 46, 85, 19,  5, 49, 68, 59, 93, 35, 29, 54]),
 tensor([ 4, 67, 60, 95]),
 tensor([37]))

In [9]:
dgl.readout_nodes(graph, 'features', op="mean").shape

torch.Size([1, 128])

In [10]:
dgl.khop_graph(graph, 1)

Graph(num_nodes=100, num_edges=300,
      ndata_schemes={'features': Scheme(shape=(128,), dtype=torch.float32)}
      edata_schemes={})

In [11]:
newgraph, _ = dgl.khop_in_subgraph(graph, [99], 2)
newgraph.nodes()

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
newgraph.ndata['_ID']

tensor([ 0, 15, 18, 20, 22, 91, 97, 99])

In [13]:
newgraph.ndata['_ID'][8]

IndexError: index 8 is out of bounds for dimension 0 with size 8