In [61]:
import torch

# 定义非零元素的位置和值
indices = torch.tensor([[0, 1, 1],
                        [2, 0, 2]])
values = torch.tensor([3, 4, 5], dtype=torch.float32)

# 创建稀疏张量
sparse_tensor = torch.sparse_coo_tensor(indices, values, [2, 3])
print("Sparse Tensor:")
print(sparse_tensor)

# 转换为稠密张量
dense_tensor = sparse_tensor.to_dense()
print("\nDense Tensor:")
print(dense_tensor)

# 矩阵相乘
dense_tensor = torch.tensor([[1, 2, 3],
                             [4, 5, 6]], dtype=torch.float32)
result = torch.sparse.mm(sparse_tensor, dense_tensor.t())
print(sparse_tensor.shape, dense_tensor.shape, dense_tensor.T.shape)
print("\nMatrix Multiplication Result:")
print(result)

# 稀疏矩阵与稠密矩阵相加
dense_tensor = torch.tensor([[0, 0, 0],
                             [1, 2, 3]], dtype=torch.float32)
result = sparse_tensor.to_dense() + dense_tensor
print("\nAddition Result:")
print(result)

# 检查稀疏性
is_sparse = sparse_tensor.is_sparse
print(f"\nIs the tensor sparse? {is_sparse}")

# 获取稀疏张量的索引和值
indices = sparse_tensor._indices()
values = sparse_tensor._values()
print(f"\nIndices:\n{indices}")
print(f"Values:\n{values}")

# 邻接矩阵的稀疏表示
indices = torch.tensor([[0, 0, 1, 2],
                        [1, 2, 2, 0]])
values = torch.tensor([1, 1, 1, 1], dtype=torch.float32)
adjacency_matrix = torch.sparse_coo_tensor(indices, values, (3, 3))

# 节点特征矩阵
features = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

# 图卷积操作
weights = torch.tensor([[0.1, 0.2, 0.5],
                        [0.3, 0.4, 0.6]], dtype=torch.float32)

print(adjacency_matrix.shape, features.shape, weights.shape)
output = torch.sparse.mm(adjacency_matrix, features).mm(weights)
print("\nGraph Convolution Output:")
print(output)

Sparse Tensor:
tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)

Dense Tensor:
tensor([[0., 0., 3.],
        [4., 0., 5.]])
torch.Size([2, 3]) torch.Size([2, 3]) torch.Size([3, 2])

Matrix Multiplication Result:
tensor([[ 9., 18.],
        [19., 46.]])

Addition Result:
tensor([[0., 0., 3.],
        [5., 2., 8.]])

Is the tensor sparse? True

Indices:
tensor([[0, 1, 1],
        [2, 0, 2]])
Values:
tensor([3., 4., 5.])
torch.Size([3, 3]) torch.Size([3, 2]) torch.Size([2, 3])

Graph Convolution Output:
tensor([[ 3.8000,  5.6000, 10.0000],
        [ 2.3000,  3.4000,  6.1000],
        [ 0.7000,  1.0000,  1.7000]])
